- hosts: all
  gather_facts: no 

  tasks:
    - name: install nginx      # устанавливаем посленю версию nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes       # обновляем лист программ у установщика apt перед установкой
      notify:                   # если этот таск произвел изменение (желтая строка),то запускается hadler с именем restart nginx после исполнения всех таксков в tasks
        - restart nginx
      become: yes               # <---  выполнить из под рута
      
    - name: stopped nginx       # останавливаем процессы nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
      notify:                   # если этот таск произвел изменение (желтая строка),то запускается hadler с именем restart nginx после исполнения всех таксков в tasks
        - restart nginx
      become: yes               # <---  выполнить из под рута

    - name: update nginx.conf     # копирум с заменой наш nginx.conf 
      ansible.builtin.template:     # копируем/заменяем файл конфига nginx при этом используя шаблонизатор j2, который подставит значиния из наших переменных vars в src файл вместо указанных в нем наших переменных, при взаиможействии с этим файломю По факту это подстановка значений шаблонизатором , как интерпритатор подставляет значения при исполнении программы использование расширения .j2 использовать не обязательно совсем 
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:                   # если этот таск произвел изменение (желтая строка), а он произвел так как мы тот только что файл вставили, то запускается hadlers с именем restart nginx после исполнения всех таксков в  tasks
        - restart nginx
      become: yes
      
    - name: Create a directory sites-available      # создаем директорию sites-available где будет хранится конфиг нашего сайта ansible.iphilka.ru.conf
      ansible.builtin.file:
        path: /etc/nginx/sites-available/
        state: directory
      become: yes                                   # <---  выполнить из под рута

    - name: Create a directory sites-enabled        # создаем директорию sites-enabled где будет хранится ярлык на конфиг нашего сайта ansible.iphilka.ru.conf 
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/             
        state: directory
      become: yes

  handlers:                         #handlers started after all tasks if in tasks be a notify with the same name 
    - name: restart nginx
      ansible.builtin.service:      # перезапускаем процессы nginx
        name: nginx
        state: reloaded            
      become: yes